version: '3'
services:
  sonarqube_server:
      build: ./sonarqube
      ports: 
        - "8001:9000"          
  sonar_scanner_dotnet:
    build: ./dotnet
    depends_on: 
      - sonarqube_server
    volumes:
      - .:/project 
    environment:
      - HOST=http://sonarqube_server:9000    
  sonar_scanner_other:
    build: ./other
    depends_on: 
      - sonarqube_server
    volumes:
      - .:/project
    environment:
      - HOST=http://sonarqube_server:9000 