version: '3'
services:
  sonarqube_server:
      build: ./sonarqube
      ports: 
        - "8001:9000"  
      environment:
        - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar   
      depends_on: 
        - db    
      restart: always 
  sonar_scanner_dotnet:
    build: ./dotnet
    depends_on: 
      - sonarqube_server    
    environment:
      - HOST=http://sonarqube_server:9000    
  sonar_scanner_other:
    build: ./other
    depends_on: 
      - sonarqube_server    
    environment:
      - HOST=http://sonarqube_server:9000 
  #dependency-check:
    #build: ./dependency-check
  db:
      image: postgres    
      environment:
        - POSTGRES_USER=sonar
        - POSTGRES_PASSWORD=sonar        
      volumes:       
        # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
        - postgres:/var/lib/postgresql/data
      restart: always 

volumes:
  postgres: 
  